language: java

jdk:
  - oraclejdk8

services:
  - mysql
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.4-precise
    packages:
    - mongodb-org-server

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;"
  - mysql -u root -e "CREATE USER 'user'@'localhost' IDENTIFIED BY 'pass';"
  - mysql -u root -e "GRANT ALL ON test.* TO 'user'@'localhost';"
  - mysql -e "USE test;"
  - mysql -e "CREATE TABLE test.cinema (
      id varchar(45) NOT NULL,
      name varchar(45) NOT NULL,
      location varchar(45) NOT NULL
    );"
  - mysql -e "CREATE TABLE test.hall (
      id varchar(45) NOT NULL,
      name varchar(45) NOT NULL,
      cinemaId varchar(45) NOT NULL
    );"
  - mysql -e "CREATE TABLE test.movie (
      id varchar(45) NOT NULL,
      name varchar(45) NOT NULL,
      duration int(11) NOT NULL,
      annotation text NOT NULL
    );"
  - mysql -e "CREATE TABLE test.session (
      id varchar(45) NOT NULL,
      sessionStart timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      movieId varchar(45) NOT NULL,
      hallId varchar(45) NOT NULL
    );"
  - mysql -e "CREATE TABLE test.ticket (
      id varchar(45) NOT NULL,
      user_id varchar(45) NOT NULL,
      row int(11) NOT NULL,
      seat int(11) NOT NULL
    );"
  - mysql -e "CREATE TABLE test.user (
      id varchar(45) NOT NULL,
      full_name varchar(45) NOT NULL,
      user_name varchar(45) NOT NULL,
      password varchar(45) NOT NULL,
      salt varchar(45) NOT NULL,
      email varchar(45) NOT NULL
    );"
  - mysql -e "ALTER TABLE test.cinema
      ADD PRIMARY KEY (id);"
  - mysql -e "ALTER TABLE test.hall
      ADD PRIMARY KEY (id);"
  - mysql -e "ALTER TABLE test.movie
      ADD PRIMARY KEY (id);"
  - mysql -e "ALTER TABLE test.session
      ADD PRIMARY KEY (id);"
  - mysql -e "ALTER TABLE test.ticket
      ADD PRIMARY KEY (id);"
  - mysql -e "ALTER TABLE test.user
      ADD PRIMARY KEY (id);"